### ISSUE TITLE
Dislocated texture

### ISSUE THREAD

**Issue by Uncle-Justice** [chaowang15/plane-opt-rgbd#3]
Hi, I tried the data from the BundleFusion's official site and it worked very well. And I built BundleFusion code on my own. The data generated by my BundleFusion code showed bad texture result in plane-opt-rgbd. I feel puzzled.

[![DTCVOK.png](https://s3.ax1x.com/2020/12/03/DTCVOK.png)](https://imgchr.com/i/DTCVOK)

The mesh partition and my original mesh seem good. But I dont know where is the problem.

Hope to get your reply, thanks.

**Comment by chaowang15** [comment]
Sorry I haven't checked this repo for a long time. What you mean is, the dataset from BundleFusion website (RGBD sequences and mesh) works, but the mesh you reconstructed from BundleFusion code doesn't work? Even with exactly the same RGBD sequence?

**Comment by chaowang15** [comment]
> Hi, I tried the data from the BundleFusion's official site and it worked very well. And I built BundleFusion code on my own. The data generated by my BundleFusion code showed bad texture result in plane-opt-rgbd. I feel puzzled.
> 
> [![DTCVOK.png](https://camo.githubusercontent.com/c79b364e908fa5c553856d01623bc3e269d72aa9d0ac49fd8f9984b53f4463ad/68747470733a2f2f73332e617831782e636f6d2f323032302f31322f30332f445443564f4b2e706e67)](https://imgchr.com/i/DTCVOK)
> 
> The mesh partition and my original mesh seem good. But I dont know where is the problem.
> 
> Hope to get your reply, thanks.

Sorry I haven't checked this repo for a long time. What you mean is, the dataset from BundleFusion website (RGBD sequences and mesh) works, but the mesh you reconstructed from BundleFusion code doesn't work? Even with exactly the same RGBD sequence?

**Comment by Uncle-Justice** [comment]
Thanks for the reply. My BundleFusion code had some subtle mistakes and it outputs a mirror symmetry between the model and the rgbd frames. This issue has been solved. 

And I got some new quesitons for texturing.

**Comment by Uncle-Justice** [comment]
#4

**Comment by Uncle-Justice** [comment]
#4 Incomplete texture
